  name : Build and Deploy
on:
  push:
    branches:
      - 'main'
      jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    - name: Checkout
  uses: actions/checkout@v1
  - name: Use Node 12.x
  uses: actions/setup-node@v1
  with:
    node-version: '12.x'
    - name: Install dependencies
  run: npm install
- name: Build
  run: npm run build
  - name: Archive build
  if: success()
  uses: actions/upload-artifact@v1
  with:
    name: deploy_dist
    path: dist
    deploy:
  runs-on: ubuntu-latest
  needs: build
  steps:
      - name: Checkout
        uses: actions/checkout@v1
        - name: Download build
  uses: actions/download-artifact@v1
  with:
    name: deploy_dist
    - name: Install surge a
    uses: actions/setup-node@v1
    with:
        node-version: '12.x'
        - run: npm install -g surge
        - run: surge ./deploy_dist/projectname ${{ secrets.SURGE_DOMAIN }} --token ${{ secrets.SURGE_TOKEN }}
